name: vendingmachineservice
favicon: null
layout_spectrum: 0.5843802443705499
typography_spectrum: 0.2650852950755507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4753453694283962
  lightness: 0.4855337382759899
  saturation: 0.04572558728978038
  rhythmicContrast: 0.381026825401932
purpose: []
