name: vending machine
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2650852950755507
title: vending machine service repair
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#baffa8'
    - '#ffb5ff'
    - '#165600'
    - '#f37a92'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
